In [1]:
import pandas as pd
from datetime import datetime, timedelta

In [8]:
# Initialize start and end times
start_time = datetime.strptime("05/06/2023 05:00", "%m/%d/%Y %H:%M")
end_time = datetime.strptime("05/06/2023 23:00", "%m/%d/%Y %H:%M")

# Generate hourly intervals
time_intervals = []
current_time = start_time
while current_time < end_time:
    next_time = current_time + timedelta(hours=1)
    time_intervals.append({"startdate": current_time, "enddate": next_time})
    current_time = next_time

# Create DataFrame
df = pd.DataFrame(time_intervals)

# Display the DataFrame
df['startdate'] = df['startdate'].map(lambda x: x.isoformat())
df['enddate'] = df['enddate'].map(lambda x: x.isoformat())
df

              startdate              enddate
0   2023-05-06T05:00:00  2023-05-06T06:00:00
1   2023-05-06T06:00:00  2023-05-06T07:00:00
2   2023-05-06T07:00:00  2023-05-06T08:00:00
3   2023-05-06T08:00:00  2023-05-06T09:00:00
4   2023-05-06T09:00:00  2023-05-06T10:00:00
5   2023-05-06T10:00:00  2023-05-06T11:00:00
6   2023-05-06T11:00:00  2023-05-06T12:00:00
7   2023-05-06T12:00:00  2023-05-06T13:00:00
8   2023-05-06T13:00:00  2023-05-06T14:00:00
9   2023-05-06T14:00:00  2023-05-06T15:00:00
10  2023-05-06T15:00:00  2023-05-06T16:00:00
11  2023-05-06T16:00:00  2023-05-06T17:00:00
12  2023-05-06T17:00:00  2023-05-06T18:00:00
13  2023-05-06T18:00:00  2023-05-06T19:00:00
14  2023-05-06T19:00:00  2023-05-06T20:00:00
15  2023-05-06T20:00:00  2023-05-06T21:00:00
16  2023-05-06T21:00:00  2023-05-06T22:00:00
17  2023-05-06T22:00:00  2023-05-06T23:00:00

In [13]:
df.to_json('hourly_intervals.json', orient='records', indent=4)